import { Flower } from "@/types/bouquet";

export const flowers: Flower[] = [
  {
    id: "rose",
    name: "Rose",
    meaning: "Love and romance",
    category: "focal",
    colors: ["pink", "red", "white", "yellow"],
    size: "large",
    layerPriority: 4,
  },
  {
    id: "peony",
    name: "Peony",
    meaning: "Prosperity and romance",
    category: "focal",
    colors: ["pink", "white", "coral"],
    size: "large",
    layerPriority: 4,
  },
  {
    id: "tulip",
    name: "Tulip",
    meaning: "Perfect love",
    category: "focal",
    colors: ["pink", "yellow", "red", "purple"],
    size: "medium",
    layerPriority: 3,
  },
  {
    id: "lily",
    name: "Lily",
    meaning: "Purity and refined beauty",
    category: "focal",
    colors: ["white", "pink", "orange"],
    size: "large",
    layerPriority: 4,
  },
  {
    id: "sunflower",
    name: "Sunflower",
    meaning: "Adoration and loyalty",
    category: "focal",
    colors: ["yellow"],
    size: "large",
    layerPriority: 4,
  },
  {
    id: "daisy",
    name: "Daisy",
    meaning: "Innocence and cheerfulness",
    category: "filler",
    colors: ["white", "yellow"],
    size: "small",
    layerPriority: 2,
  },
  {
    id: "orchid",
    name: "Orchid",
    meaning: "Luxury and strength",
    category: "focal",
    colors: ["purple", "white", "pink"],
    size: "medium",
    layerPriority: 3,
  },
  {
    id: "hydrangea",
    name: "Hydrangea",
    meaning: "Gratitude and heartfelt emotion",
    category: "focal",
    colors: ["blue", "pink", "white"],
    size: "large",
    layerPriority: 4,
  },
  {
    id: "lavender",
    name: "Lavender",
    meaning: "Serenity and grace",
    category: "accent",
    colors: ["purple"],
    size: "small",
    layerPriority: 1,
  },
  {
    id: "babys_breath",
    name: "Baby's Breath",
    meaning: "Everlasting love",
    category: "filler",
    colors: ["white"],
    size: "small",
    layerPriority: 1,
  },
  {
    id: "carnation",
    name: "Carnation",
    meaning: "Fascination and love",
    category: "filler",
    colors: ["pink", "red", "white"],
    size: "medium",
    layerPriority: 2,
  },
  {
    id: "ranunculus",
    name: "Ranunculus",
    meaning: "Charm and attractiveness",
    category: "focal",
    colors: ["orange", "pink", "yellow", "white"],
    size: "medium",
    layerPriority: 3,
  },
  {
    id: "anemone",
    name: "Anemone",
    meaning: "Anticipation and excitement",
    category: "accent",
    colors: ["red", "purple", "white"],
    size: "medium",
    layerPriority: 2,
  },
  {
    id: "freesia",
    name: "Freesia",
    meaning: "Innocence and thoughtfulness",
    category: "accent",
    colors: ["yellow", "pink", "white"],
    size: "small",
    layerPriority: 1,
  },
  {
    id: "lisianthus",
    name: "Lisianthus",
    meaning: "Gratitude and appreciation",
    category: "filler",
    colors: ["purple", "white", "blue"],
    size: "medium",
    layerPriority: 2,
  },
  {
    id: "iris",
    name: "Iris",
    meaning: "Wisdom and hope",
    category: "accent",
    colors: ["purple", "blue", "yellow"],
    size: "medium",
    layerPriority: 2,
  },
  {
    id: "cherry_blossom",
    name: "Cherry Blossom",
    meaning: "Renewal and beauty of life",
    category: "accent",
    colors: ["pink"],
    size: "small",
    layerPriority: 1,
  },
  {
    id: "dahlia",
    name: "Dahlia",
    meaning: "Commitment and bond",
    category: "focal",
    colors: ["red", "pink", "orange", "white"],
    size: "large",
    layerPriority: 4,
  },
  {
    id: "marigold",
    name: "Marigold",
    meaning: "Passion and creativity",
    category: "accent",
    colors: ["orange", "yellow"],
    size: "small",
    layerPriority: 1,
  },
  {
    id: "jasmine",
    name: "Jasmine",
    meaning: "Grace and elegance",
    category: "accent",
    colors: ["white"],
    size: "small",
    layerPriority: 1,
  },
  {
    id: "lotus",
    name: "Lotus",
    meaning: "Purity and enlightenment",
    category: "focal",
    colors: ["pink", "white"],
    size: "medium",
    layerPriority: 3,
  },
  {
    id: "hibiscus",
    name: "Hibiscus",
    meaning: "Delicate beauty",
    category: "focal",
    colors: ["red", "pink", "yellow"],
    size: "large",
    layerPriority: 4,
  },
  {
    id: "camellia",
    name: "Camellia",
    meaning: "Admiration and perfection",
    category: "focal",
    colors: ["pink", "white", "red"],
    size: "medium",
    layerPriority: 3,
  },
  {
    id: "bluebell",
    name: "Bluebell",
    meaning: "Gratitude and humility",
    category: "filler",
    colors: ["blue"],
    size: "small",
    layerPriority: 1,
  },
  {
    id: "poppy",
    name: "Poppy",
    meaning: "Rest and remembrance",
    category: "accent",
    colors: ["red", "orange", "yellow"],
    size: "medium",
    layerPriority: 2,
  },
];

export function getFlowerById(id: string): Flower | undefined {
  return flowers.find((f) => f.id === id);
}

export function getFlowersByCategory(
  category: Flower["category"]
): Flower[] {
  return flowers.filter((f) => f.category === category);
}

export function getFlowersByColor(color: string): Flower[] {
  return flowers.filter((f) => f.colors.includes(color));
}
